### ISSUE TITLE
Just wanted to say thanks.

### ISSUE THREAD

**Issue by xzyxzy** [ByPrinciple/GT7-Scripts#1]
Hey, too lazy to register on psnprofiles but I just wanted to say thanks
Just had clean win10 x64 on vmware that I was testing was my own janky AHK script but yours is much better and stable.
Had no need to tweak anything it just worked as per instructions.

**Comment by ByPrinciple** [comment]
If you're interested in contributions at any point just let me know. Want to expand to other races and such and not too many are familiar with ahk to begin with.
